################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f64.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q15.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q31.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q7.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f64.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q15.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q31.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q7.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f64.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q15.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q31.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q7.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f64.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q15.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q31.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q7.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f64.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q15.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q31.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q7.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_q15.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_q31.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f64.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_q15.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_q31.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f16.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f32.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f64.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_q15.c \
../Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_q31.c 

OBJS += \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f64.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q15.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q31.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q7.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f64.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f64.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q15.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q31.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q7.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f64.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q15.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q31.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q7.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f64.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q15.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q31.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q7.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f64.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_q15.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_q31.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f16.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f32.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f64.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_q15.o \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_q31.o 

C_DEPS += \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f64.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q15.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q31.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q7.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f64.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f64.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q15.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q31.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q7.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f64.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q15.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q31.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q7.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f64.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q15.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q31.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q7.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f64.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_q15.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_q31.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f16.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f32.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f64.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_q15.d \
./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_q31.d 


# Each subdirectory must supply rules for building sources it contributes
Driver/CSMIS/DSP/Source/StatisticsFunctions/%.o Driver/CSMIS/DSP/Source/StatisticsFunctions/%.su Driver/CSMIS/DSP/Source/StatisticsFunctions/%.cyclo: ../Driver/CSMIS/DSP/Source/StatisticsFunctions/%.c Driver/CSMIS/DSP/Source/StatisticsFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F4 -DSTM32F407VGTx -c -I../Inc -I"D:/Github/STM32F4/Peripheral/inc" -I"D:/Github/STM32F4/DSP" -I"D:/Github/STM32F4/DSP/Day1" -I"D:/Github/STM32F4/Driver/Core/Inc" -I"D:/Github/STM32F4/Peripheral" -I"D:/Github/STM32F4/Driver/CSMIS" -I"D:/Github/STM32F4/Driver/CSMIS/Device/ST/STM32F4xx/Include" -I"D:/Github/STM32F4/Driver/CSMIS/Core/Include" -I"D:/Github/STM32F4/Driver/CSMIS/DSP/Include" -I"D:/Github/STM32F4/Driver/CSMIS/Include" -I"D:/Github/STM32F4/Peripheral/src" -I"D:/Github/STM32F4/Driver/CSMIS/DSP/PrivateInclude" -I"D:/Github/STM32F4/Driver/CSMIS/DSP/ComputeLibrary" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Driver-2f-CSMIS-2f-DSP-2f-Source-2f-StatisticsFunctions

clean-Driver-2f-CSMIS-2f-DSP-2f-Source-2f-StatisticsFunctions:
	-$(RM) ./Driver/CSMIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o
	-$(RM) ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f64.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f64.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f64.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_f64.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o
	-$(RM) ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q15.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q15.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q15.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q15.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q31.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q31.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q31.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q31.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q7.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q7.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q7.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_max_q7.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f64.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f64.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f64.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_f64.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q15.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q15.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q31.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q31.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q7.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mean_q7.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f64.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f64.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f64.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_f64.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q15.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q15.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q15.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q15.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q31.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q31.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q31.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q31.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q7.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q7.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q7.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_min_q7.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f32.cyclo
	-$(RM) ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f64.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f64.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f64.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_f64.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q15.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q15.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q15.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q15.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q31.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q31.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q31.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q31.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q7.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q7.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q7.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_mse_q7.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f64.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f64.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f64.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_f64.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q15.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q15.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q15.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q15.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q31.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q31.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q31.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q31.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q7.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q7.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q7.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_power_q7.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_q15.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_q15.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_q31.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_rms_q31.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f64.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f64.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f64.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_f64.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_q15.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_q15.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_q15.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_q15.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_q31.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_q31.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_q31.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_std_q31.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f16.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f16.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f16.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f16.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f32.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f32.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f32.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f32.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f64.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f64.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f64.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_f64.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_q15.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_q15.d ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_q15.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_q15.su ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_q31.cyclo ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_q31.d
	-$(RM) ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_q31.o ./Driver/CSMIS/DSP/Source/StatisticsFunctions/arm_var_q31.su

.PHONY: clean-Driver-2f-CSMIS-2f-DSP-2f-Source-2f-StatisticsFunctions

