///**
// ******************************************************************************
// * @file           : main.c
// * @author         : Auto-generated by STM32CubeIDE
// * @brief          : Main program body
// ******************************************************************************
// * @attention
// *
// * Copyright (c) 2026 STMicroelectronics.
// * All rights reserved.
// *
// * This software is licensed under terms that can be found in the LICENSE file
// * in the root directory of this software component.
// * If no LICENSE file comes with this software, it is provided AS-IS.
// *
// ******************************************************************************
// */
//
//#include <stdint.h>
//#include <stdio.h>
//
//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif
//#define ADC_BASE_ADDR   			0x40012000UL
//
//#define ADC_CR1_REG_OFFSET 			0x04UL
//
//#define ADC_CR1_REG_ADDR  			(ADC_BASE_ADDR + ADC_CR1_REG_OFFSET )
//
//#define RCC_BASE_ADDR              0x40023800UL
//
//#define RCC_APB2_ENR_OFFSET        0x44UL
//
//#define RCC_APB2_ENR_ADDR          (RCC_BASE_ADDR + RCC_APB2_ENR_OFFSET )
//int main(void)
//{
//	int a=0;
//	a++;
//	printf("hello lucas%d\n",a);
//	uint32_t *pAdcCr1Reg =   (uint32_t*) ADC_CR1_REG_ADDR;
//	uint32_t *pRccApb2Enr =  (uint32_t*) RCC_APB2_ENR_ADDR;
//
//	//1.Enable the peripheral clock for ADC1
//	*pRccApb2Enr |= ( 1 << 8);
//
//    //2. modify the ADC cr1 register
//	*pAdcCr1Reg |= ( 1 << 8);
//    /* Loop forever */
//	for(;;);
//
//}
	//#include "stm32f407xx.h"
#include "stm32f4xx_drivers.h"
//#include "stm32f407xx.h"
#include "st7735.h"
#include "signals.h"
#include "ecg.h"
#include "arm_math.h"
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
GPIO_Handle_t hgpiod;
//GPIO_Handle_t hgpioa;
GPIO_Handle_t hgpiob;
//SPI_Handle_t hspi2;
uint32_t cnt=0;
float32_t g_in_sig_sample=0.0f;
float32_t g_in_convolution_signal=0.0f;
float32_t convoulution_signals[_1kHz_15kHz_SIG_LEN+IMPULSE_RESPOND_LEN-1]={0.0f};
float32_t running_sum_signals[ECG_SIGNAL_LEN]={0.0f};

float32_t dft_real[DFT_BINS]={0.0f};
float32_t dft_imag[DFT_BINS]={0.0f};
float32_t dft_magnitude[DFT_BINS]={0.0f};
void EnableFPU()
{
	SCB->CPACR |=(3UL<<22)|(3UL<<20);
}
float32_t _mean_result = 0.0f;
float32_t _standard_deviation_result = 0.0f;
float32_t _variance_result = 0.0f;
uint32_t _val_start_measure=0u;
uint32_t _val_end_measure=0u;
float32_t _val_result_measure=0.0f;

//void CMSIS_DSP_Test(void)
//{
//
//    arm_mean_f32(_5hz_signal, HZ_5_SIG_LEN, (float32_t *)&cmsis_mean_result);
//}

//void SPI2_Inits()
//{
//	hspi2.pSPIx=SPI2;
//	hspi2.SPIConfig.SPI_DeviceMode=SPI_DEVICE_MODE_MASTER;
//	hspi2.SPIConfig.SPI_BusConfig=SPI_BUS_CONFIG_FD;
//	hspi2.SPIConfig.SPI_DFF=SPI_DFF_8bits;
//	hspi2.SPIConfig.SPI_Frame_format=MSB_TRANSMITTED_FIRST;
//	hspi2.SPIConfig.SPI_SSM=SPI_SSM_EN;
//	hspi2.SPIConfig.SPI_CPHA=SPI_CPHA_LOW;
//	hspi2.SPIConfig.SPI_CPOL=SPI_CPOL_LOW;
//	hspi2.SPIConfig.speed=SPI_SCLK_SPEED_DIV8;
//	SPI_Init(&hspi2);
//}
//	void SPI_ApplicationEvntCallback(SPI_Handle_t *pSPIhandle,uint8_t AppEvent)
//	{
//		if(pSPIhandle->pSPIx==SPI2)
//		{
//			if(AppEvent==SPI_EVENT_TX_CMP)
//			{
//					GPIO_Write_Pin(&gpiod,GPIO_PIN_NO_13,SET);
//					SPI_SendDataIT(&spi2,(uint8_t*)"hello lucas",strlen("hello lucas"));
//			}
//		}
//
//	}
//void Dashboard_Init() {
//    tft.hspi = &hspi2;
//    tft.GPIO_portCs = GPIOD; tft.GPIO_Pin_Cs = GPIO_PIN_NO_12;
//    tft.GPIO_portA0 = GPIOB; tft.GPIO_Pin_A0 = GPIO_PIN_NO_10;
//    tft.GPIO_portRESET = GPIOB; tft.GPIO_Pin_Reset = GPIO_PIN_NO_11;
//    tft.GPIO_portBL = GPIOB; tft.GPIO_Pin_BL =GPIO_PIN_NO_12;
//    ST7735_Backlight_On();
//    ST7735_Init();
//    ST7735_SetRotation(1);
//}


volatile char buffer[32];
volatile uint32_t buffer_index = 0;

void UART_init()
{
    volatile uint32_t *RCC_APB2ENR = (volatile uint32_t *)(0x40023800 + 0x44);
    volatile uint32_t *USART_CR1   = (volatile uint32_t *)(USART1_BASE + 0x0C);
    volatile uint32_t *USART_BRR   = (volatile uint32_t *)(USART1_BASE + 0x08);
    volatile uint32_t *ISER1       = (volatile uint32_t *)(0xE000E104);

    // Bật clock USART1
    *RCC_APB2ENR |= (1 << 4);

    // Tắt USART trước khi config
    *USART_CR1 = 0;

    // BRR đúng cho 115200 @ 16MHz
    *USART_BRR = (8U << 4) | 11U;

    // Bật UE + TE + RE + RXNEIE
    *USART_CR1 = (1<<13)|(1<<3)|(1<<2)|(1<<5);

    // NVIC USART1 IRQ37
    *ISER1 |= (1 << (37 - 32));
}

void UartSend1Byte(char c)
{
	volatile uint32_t *USART_SR = (volatile uint32_t *)(USART1_BASE);
	volatile uint32_t *USART_DR = (volatile uint32_t *)(USART1_BASE + 0x04);

    // Chờ cờ TXE (Transmit data register empty) - Bit 7
	while (((*USART_SR >> 7) & 1) == 0);
	*USART_DR = (uint8_t)c;

//    // Chờ cờ TC (Transmission complete) - Bit 6
//	while (((*USART_SR >> 6) & 1) == 0);
    // Xóa cờ TC
	*USART_SR &= ~(0b1 << 6);
}

void UartSendString(char *str)
{
    // Tính strlen 1 lần thôi cho tối ưu
    uint32_t len = strlen(str);
	for(uint32_t i = 0; i < len; i++)
	{
		UartSend1Byte(str[i]);
	}
}

// Hàm ngắt
void USART1_IRQHandler()
{
	volatile uint32_t *USART_SR = (volatile uint32_t *)(USART1_BASE);
	volatile uint32_t *USART_DR = (volatile uint32_t *)(USART1_BASE + 0x04);

    // Kiểm tra xem ngắt có thực sự do RXNE gây ra không (an toàn nhất)
    if (((*USART_SR >> 5) & 1) == 1)
    {
        // Đọc DR tự động xóa cờ RXNE
        buffer[buffer_index] = *USART_DR;
        buffer_index = (buffer_index + 1) % 32;

        // Toggle LED để debug
        GPIO_Toggle_Pin(&hgpiod, GPIO_PIN_NO_12);
    }
}
void print(const char *fmt, ...)
{
    char buf[160];
    va_list args;
    int len;

    va_start(args, fmt);
    len = vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);

    if (len <= 0) {
        return;
    }

    if (len > (int)sizeof(buf)) {
        len = (int)sizeof(buf);
    }

    UartSendString(buf);
   // GPIO_Toggle_Pin(&hgpiod, GPIO_PIN_NO_13);
}
void serial_plot_signals(const char *fmt, ...)
{
	va_list args;
	char buf[5000];
	int len;

	va_start(args, fmt);
	len = vsnprintf(buf, sizeof(buf), fmt, args);
	va_end(args);

	if (len <= 0) {
		return;
	}

	if (len > (int)sizeof(buf)) {
		len = (int)sizeof(buf);
	}

	UartSendString(buf);
}

void systick_init()
{
	// disablled SysTick
	SysTick->CTRL=0;
	//CLKSRC
	SysTick->CTRL|=1<<2;
	//reload value
	SysTick->LOAD=0x00FFFFFF;
	//
	SysTick->VAL=0;
	//
	SysTick->CTRL|=1<<0;
}

volatile uint8_t flag=0;
volatile uint8_t flag1=0;
int main(void) {
	// /* 1. Bật clock cho GPIOD */
//	RCC->AHB1ENR |= (1 << 3);     // GPIODEN = bit 3
	EnableFPU();
	systick_init();
	hgpiod.pGPIOx= GPIOD;
	hgpiod.GPIO_PinConfig.GPIO_PinNumber= GPIO_PIN_NO_13;
	hgpiod.GPIO_PinConfig.GPIO_PinMode= GPIO_MODE_OUT;
	hgpiod.GPIO_PinConfig.GPIO_PinOPType= GPIO_OP_TYPE_PP;
	hgpiod.GPIO_PinConfig.GPIO_PinPuPdControl= GPIO_NO_PUPD;
	hgpiod.GPIO_PinConfig.GPIO_PinSpeed= GPIO_SPEED_HIGH;
	GPIO_Init(&hgpiod);
	hgpiod.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GPIO_Init(&hgpiod);

//	hgpiod.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
//	GPIO_Init(&hgpiod);

	hgpiod.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
	GPIO_Init(&hgpiod);

	 hgpiod.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
	 GPIO_Init(&hgpiod);

//	 hgpiob.pGPIOx= GPIOB;
//	 	hgpiob.GPIO_PinConfig.GPIO_PinNumber= GPIO_PIN_NO_10;
//	 	hgpiob.GPIO_PinConfig.GPIO_PinMode= GPIO_MODE_OUT;
//	 	hgpiob.GPIO_PinConfig.GPIO_PinOPType= GPIO_OP_TYPE_PP;
//	 	hgpiob.GPIO_PinConfig.GPIO_PinPuPdControl= GPIO_NO_PUPD;
//	 	hgpiob.GPIO_PinConfig.GPIO_PinSpeed= GPIO_SPEED_HIGH;
//	 	GPIO_Init(&hgpiob);
//	 	hgpiob.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_11;
//	 	GPIO_Init(&hgpiob);
//	 	hgpiob.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
//	 	GPIO_Init(&hgpiob);
	// hgpioa.pGPIOx= GPIOA;
	// hgpioa.GPIO_PinConfig.GPIO_PinNumber= GPIO_PIN_NO_0;
	// hgpioa.GPIO_PinConfig.GPIO_PinMode= GPIO_MODE_IT_FT;
	// hgpioa.GPIO_PinConfig.GPIO_PinPuPdControl= GPIO_NO_PUPD;
	// GPIO_Init(&hgpioa);

	//rcc_init();
	// Timer_init();
	// NVIC_ICSR(EXTI0_IRQn,ENABLE);
	// Driver_NVIC_SetPriorityGrouping();
	// Driver_NVIC_SetPriority(EXTI0_IRQn,0,0);
//	SPI_GpioConfig(SPI2);
//	SPI2_Inits();
//	SPI_SSI_Config(SPI2,ENABLE);
//	SPI_PeripheralControl(SPI2,ENABLE);
////		SPI_IRQInteruptPriority(SPI2,0,1);
////		SPI_IRQInteruptConfig(SPI2,ENABLE);
//	Dashboard_Init();
//	ST7735_FillScreen(ST7735_RED);
//	ST7735_DrawString(20, 40, "luca  ss", &Font_7x10, ST7735_RED, ST7735_WHITE);
//	ST7735_DrawString(20, 40, "lucass", &Font_7x10, ST7735_RED, ST7735_WHITE);
//	delay_ms(500);
//	ST7735_FillScreen(ST7735_RED);
//	ST7735_Backlight_Off();
//	ST7735_Backlight_On();
//	ST7735_DrawPixel(20, 40, ST7735_RED);

	hgpiob.pGPIOx=GPIOB;
	hgpiob.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;       // Chế độ là Alternate Function
	hgpiob.GPIO_PinConfig.GPIO_PinAltFunMode = AF7;
	hgpiob.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PP;
	hgpiob.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_PIN_PU;
	hgpiob.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_6;
	GPIO_Init(&hgpiob);
	hgpiob.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_7;
	GPIO_Init(&hgpiob);
	UART_init();
	//CMSIS_DSP_Test();
	mean_signals(_5hz_signal, (uint32_t)HZ_5_SIG_LEN,&_mean_result);
	variance_sample_signals(_5hz_signal,(uint32_t)HZ_5_SIG_LEN,&_variance_result);
	standard_deviation_sample_signals(_5hz_signal,(uint32_t)HZ_5_SIG_LEN,&_standard_deviation_result);

	while (1) {
		//ST7735_FillScreen(ST7735_RED);
		//GPIO_Toggle_Pin(GPIOD,GPIO_PIN_NO_13);
	//	delay_ms(500);
		plot_input_signal();
		_val_start_measure=SysTick->VAL;
		//convolution_signals(inputSignal_f32_1kHz_15kHz,impulse_response,convoulution_signals,_1kHz_15kHz_SIG_LEN,IMPULSE_RESPOND_LEN);
		//arm_conv_f32(inputSignal_f32_1kHz_15kHz, _1kHz_15kHz_SIG_LEN, impulse_response,IMPULSE_RESPOND_LEN ,convoulution_signals );

		//running_sum_average(ecg_signal,ECG_SIGNAL_LEN,running_sum_signals);
		dft_real_one_sided_f32(
			ecg_signal,
		    DFT_N,
		    dft_real,
		    dft_imag,
		    dft_magnitude,
		    DFT_BINS
		);
		for ( int i=0;i<DFT_BINS;i++)
			{
				serial_plot_signals("$%.5f %.5f;",dft_magnitude[i],ecg_signal[i]);
			}
		_val_end_measure=SysTick->VAL;
		_val_result_measure=1.0*(_val_start_measure-_val_end_measure)/16000000;
		pesudo_delay(1000);

	}

}


//void EXTI0_IRQCallback(uint8_t GPIO_PinNumber)
//{
//	if(GPIO_PinNumber == GPIO_PIN_NO_0)
//	{
//		delay_ms(50);
//		if(GPIO_Read_Pin(GPIOA,0)){
//		flag=1;
//		GPIO_Toggle_Pin(GPIOD,GPIO_PIN_NO_14);
//		flag1++;
//		}
//	}
//}


