################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/ControllerFunctions.c \
D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_f32.c \
D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q15.c \
D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q31.c \
D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_f32.c \
D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q15.c \
D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q31.c \
D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_f32.c \
D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_q31.c 

OBJS += \
./Driver/CMSIS/DSP/Source/ControllerFunctions/ControllerFunctions.o \
./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_f32.o \
./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q15.o \
./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q31.o \
./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_f32.o \
./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q15.o \
./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q31.o \
./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_f32.o \
./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_q31.o 

C_DEPS += \
./Driver/CMSIS/DSP/Source/ControllerFunctions/ControllerFunctions.d \
./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_f32.d \
./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q15.d \
./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q31.d \
./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_f32.d \
./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q15.d \
./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q31.d \
./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_f32.d \
./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_q31.d 


# Each subdirectory must supply rules for building sources it contributes
Driver/CMSIS/DSP/Source/ControllerFunctions/ControllerFunctions.o: D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/ControllerFunctions.c Driver/CMSIS/DSP/Source/ControllerFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F4 -DSTM32F407VGTx -c -I../Inc -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Core/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"D:/Github/stm32/stm32_linux_F4/Core/Inc" -I"D:/Github/STM32F4/Peripheral/inc" -I"D:/Github/STM32F4/DSP" -I"D:/Github/STM32F4/DSP/Day1" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/PrivateInclude" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_f32.o: D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_f32.c Driver/CMSIS/DSP/Source/ControllerFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F4 -DSTM32F407VGTx -c -I../Inc -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Core/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"D:/Github/stm32/stm32_linux_F4/Core/Inc" -I"D:/Github/STM32F4/Peripheral/inc" -I"D:/Github/STM32F4/DSP" -I"D:/Github/STM32F4/DSP/Day1" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/PrivateInclude" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q15.o: D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q15.c Driver/CMSIS/DSP/Source/ControllerFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F4 -DSTM32F407VGTx -c -I../Inc -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Core/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"D:/Github/stm32/stm32_linux_F4/Core/Inc" -I"D:/Github/STM32F4/Peripheral/inc" -I"D:/Github/STM32F4/DSP" -I"D:/Github/STM32F4/DSP/Day1" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/PrivateInclude" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q31.o: D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q31.c Driver/CMSIS/DSP/Source/ControllerFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F4 -DSTM32F407VGTx -c -I../Inc -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Core/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"D:/Github/stm32/stm32_linux_F4/Core/Inc" -I"D:/Github/STM32F4/Peripheral/inc" -I"D:/Github/STM32F4/DSP" -I"D:/Github/STM32F4/DSP/Day1" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/PrivateInclude" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_f32.o: D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_f32.c Driver/CMSIS/DSP/Source/ControllerFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F4 -DSTM32F407VGTx -c -I../Inc -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Core/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"D:/Github/stm32/stm32_linux_F4/Core/Inc" -I"D:/Github/STM32F4/Peripheral/inc" -I"D:/Github/STM32F4/DSP" -I"D:/Github/STM32F4/DSP/Day1" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/PrivateInclude" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q15.o: D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q15.c Driver/CMSIS/DSP/Source/ControllerFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F4 -DSTM32F407VGTx -c -I../Inc -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Core/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"D:/Github/stm32/stm32_linux_F4/Core/Inc" -I"D:/Github/STM32F4/Peripheral/inc" -I"D:/Github/STM32F4/DSP" -I"D:/Github/STM32F4/DSP/Day1" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/PrivateInclude" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q31.o: D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q31.c Driver/CMSIS/DSP/Source/ControllerFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F4 -DSTM32F407VGTx -c -I../Inc -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Core/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"D:/Github/stm32/stm32_linux_F4/Core/Inc" -I"D:/Github/STM32F4/Peripheral/inc" -I"D:/Github/STM32F4/DSP" -I"D:/Github/STM32F4/DSP/Day1" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/PrivateInclude" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Driver/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_f32.o: D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_f32.c Driver/CMSIS/DSP/Source/ControllerFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F4 -DSTM32F407VGTx -c -I../Inc -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Core/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"D:/Github/stm32/stm32_linux_F4/Core/Inc" -I"D:/Github/STM32F4/Peripheral/inc" -I"D:/Github/STM32F4/DSP" -I"D:/Github/STM32F4/DSP/Day1" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/PrivateInclude" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Driver/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_q31.o: D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_q31.c Driver/CMSIS/DSP/Source/ControllerFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32 -DSTM32F4 -DSTM32F407VGTx -c -I../Inc -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Core/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"D:/Github/stm32/stm32_linux_F4/Core/Inc" -I"D:/Github/STM32F4/Peripheral/inc" -I"D:/Github/STM32F4/DSP" -I"D:/Github/STM32F4/DSP/Day1" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/Include" -I"D:/Github/stm32/stm32_linux_F4/Drivers/CMSIS/DSP/PrivateInclude" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

clean: clean-Driver-2f-CMSIS-2f-DSP-2f-Source-2f-ControllerFunctions

clean-Driver-2f-CMSIS-2f-DSP-2f-Source-2f-ControllerFunctions:
	-$(RM) ./Driver/CMSIS/DSP/Source/ControllerFunctions/ControllerFunctions.cyclo ./Driver/CMSIS/DSP/Source/ControllerFunctions/ControllerFunctions.d ./Driver/CMSIS/DSP/Source/ControllerFunctions/ControllerFunctions.o ./Driver/CMSIS/DSP/Source/ControllerFunctions/ControllerFunctions.su ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_f32.cyclo ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_f32.d ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_f32.o ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_f32.su ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q15.cyclo ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q15.d ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q15.o ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q15.su ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q31.cyclo ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q31.d ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q31.o ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q31.su ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_f32.cyclo ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_f32.d ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_f32.o ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_f32.su ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q15.cyclo ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q15.d ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q15.o ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q15.su ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q31.cyclo ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q31.d ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q31.o ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q31.su ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_f32.cyclo ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_f32.d ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_f32.o ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_f32.su ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_q31.cyclo ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_q31.d ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_q31.o ./Driver/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_q31.su

.PHONY: clean-Driver-2f-CMSIS-2f-DSP-2f-Source-2f-ControllerFunctions

